// <auto-generated />
namespace TrafficPolice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fixBD12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixBD12));
        
        string IMigrationMetadata.Id
        {
            get { return "202102191153051_fixBD12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
